# Generated by Django 3.0.7 on 2020-07-01 16:39

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tradingplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='companyName',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
